name: CD - Deploy Terraform infra

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker image"]
    types:
      - completed

env:
  RESOURCE_GROUP: rg-bbmetrics

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/container-apps

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/CLI@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve