name: Terraform Destroy AKS
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

permissions:
  contents: read

jobs:
  destroy:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init
      working-directory: infra/aks
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -target=azurerm_kubernetes_cluster.bbmetrics
      working-directory: infra/aks
